import Register from '@/components/Partials/auth/register';
import Head from 'next/head';
import { Grid } from '@mui/material';

const register = () => {
  return (
  <>
    <Head>
      <title>Harbor Hotel</title>
      <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    
    <Grid container justifyContent="center" alignItems="center" sx={{ m: '2% 0' }}>
      <Register />
    </Grid>
  </>
  );
};

export default register;