import Head from 'next/head';
import { Inter } from 'next/font/google'
import Sidebar from '@/components/Sidebar';
import Dashboard from '@/components/DashboardContent';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Harbor Hotel</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="/style.css" />
        <link
          rel="stylesheet"
          href="https://maxst.icons8.com/vue-static/landings/line-awesome/line-awesome/1.3.0/css/line-awesome.min.css"
        />
      </Head>
      <div className="flex">
        <Sidebar />
        <Dashboard />
      </div>
    </>
  )
}
