import TimeTablesTable from '@/components/Tools/TimeTables/timeTable';
import Head from 'next/head';

const timeTable = () => {
  return (
  <>
      <Head>
      <title>dd Hotel</title>
      <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

      <TimeTablesTable />
  </>
  );
};

export default timeTable;